# Application properties

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: fin-server

management:
  endpoint:
    health:
      show-details: always


